image: docker:latest

variables:
  IMAGE_NAME: dohyun63/admin-page
  IMAGE_TAG: latest

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker save -o image.tar $IMAGE_NAME:$IMAGE_TAG
  artifacts:
    paths:
      - image.tar   

deploy:
  stage: deploy
  script:
    - echo "$LIGHTSAIL_SSH_PRIVATE_KEY" > deploy_key.pem
    - chmod 600 deploy_key.pem
    - scp -o StrictHostKeyChecking=no -i deploy_key.pem image.tar $LIGHTSAIL_USER@$LIGHTSAIL_HOST:~
    - |
      ssh -i deploy_key.pem -o StrictHostKeyChecking=no $LIGHTSAIL_USER@$LIGHTSAIL_HOST bash -s <<EOF
        set -e
        IMAGE_NAME="$IMAGE_NAME"
        IMAGE_TAG="$IMAGE_TAG"

        docker load < ~/image.tar

        if [ "\$(docker ps -q -f name=frontend)" ]; then
          docker stop frontend
          docker rm frontend
        fi
        
        docker run -d --name frontend -p 80:80 $IMAGE_NAME:$IMAGE_TAG
        rm ~/image.tar
      EOF